# config/packages/nelmio_api_doc.yaml
nelmio_api_doc:
    areas:
        path_patterns: # an array of regexps
            - ^/api(?!/doc$)
    documentation:
        info:
            title: BileMo
            description: Votre application BileMo ! Consultez la liste des téléphones et gérez vos propres utilisateurs !
            version: 1.0.0
        components:
            securitySchemes:
                Bearer:
                    type: apiKey
                    description: 'Value: Bearer {Json Web Token}'
                    name: Authorization
                    in: header
        paths:
            /api/login_check:
                post:
                    summary: 'Login into the api with a JWT'
                    tags:
                        - Login
                    requestBody:
                        description: 'Customer resource'
                        required: true
                        content:
                            application/json:
                                schema:
                                    properties:
                                        username:
                                            type: string
                                        password:
                                            type: string
                                    type: object
                    responses:
                        200:
                            description: get json web token
                            content:
                                application/json:
                                    schema:
                                        type: object
                                        properties:
                                            token:
                                                type: string
                        400:
                            description: Invalid JSON
                        401:
                            description: Invalid credentials
                    security: []
        security:
            - Bearer: []
    models:
        names:
            - { alias: Phone, type: App\Entity\Phone, groups: [show_phones] }
            - { alias: Phone_list, type: App\Entity\Phone, groups: [list_phones] }
            - { alias: User, type: App\Entity\User, groups: [show_users] }
            - { alias: User_list, type: App\Entity\User, groups: [list_users] }
          